Главная страница сайта
htmlacademy-htmlcss/1801333-sedona-31 pull request #1
Opened 2021-05-23 05:12 UTC by Kubik1979

2021-05-29 11:03 UTC, Likita requested changes

2021-05-29 11:03 UTC, Likita commented on catalog.html
> +        <li><a href="twitter.com">Twitter</a></li>
В случае ссылок на сторонние ресурсы, ссылку надо указывать начиная с протокола, иначе ссылка будет распознана как на папку внутри твоего проекта.

2021-05-29 11:03 UTC, Likita commented on index.html
> +        <p>#visitsedona<br>
Лучше в отдельные span

2021-05-29 11:03 UTC, Likita commented on index.html
> +</html>
Одна пустая строка в конце каждого файла.

2021-05-29 11:53 UTC, Kubik1979 commented
 Вот тут немного не понятно про отдельные spanIn index.html:> +      <h2>Мало<br>
+        туристов</h2>
+      <span>&ndash; №5 &ndash;</span>
+      <p>Большинство едет в гранд-каньон и<br>
+        толпится там</p>
+    </section>
+    <section>
+      <h2>Заинтересовались?</h2>
+      <p>Укажите предполагаемые даты поездки,<br />
+        и мы покажем вам лучшие предложения гостиниц в седоне</p>
+      <a href="#">Поиск гостиницы в Седоне</a>
+    </section>
+    <footer>
+      <section>
+        <h3>Наш хэштег и телефон:</h3>
+        <p>#visitsedona<br>
Лучше в отдельные span 29.05.2021, 14:03, "Vasilika" ***@***.***>: @Likita requested changes on this pull request.In catalog.html:> +  <header>
+          <a href="index.html"><img src="img/header_logo.png" width="138" height="70" alt="Лого"></a>
+      <nav>
+        <ul>
+          <li><a href="#">Информация</a></li>
+          <li><a href="#">Фото и видео</a></li>
+          <li><a href="#">Карта штата</a></li>
+        </ul>
+      </nav>
+
+  </header>
+  <main>
+  <section>
+    <form>
+      <h2>Инфраструктура:</h2>
+      <input type="checkbox" name="pool" value="Бассейн" id="checkbox01" checked>
Вместо checkbox01 лучше использовать названия по смыслу, например, checkbox-pool.In catalog.html:> +  </section>
+  <section>
+    <ul>
+      <li><a href="#"><span></span></a></li>
+      <li><a><span></span></a></li>
+    </ul>
+  </section>
+  <section>
+    <article>
+      <img src="img/amara-resort_preview.jpg" width="135" height="90" alt="" />
+      <h2><a href="#">Amara resort &amp; spa</a></h2>
+      <span>Гостиница</span><br>
+      <a href="#">Подробнее</a>
+      <span>От 3500 р.</span><br>
+      <a href="#">Забронировать</a>
+      <span></span><span></span><span></span><span></span>
Пустые на будущее?In catalog.html:> +    <section>
+      <h3>Мы в соц. сетях:</h3>
+      <ul>
+        <li><a href="twitter.com">Twitter</a></li>
+        <li><a href="facebook.com">Facebook</a></li>
+        <li><a href="youtube.com">YouTube</a></li>
+      </ul>
+    </section>
+    <section>
+      <a href="https://htmlacademy.ru/intensive/htmlcss">Website by</a>
+    </section>
+  </footer>
+  </main>
+</body>
+
+</html>
Добавить пустую строку в конце файла.In catalog.html:> +      <a href="#">Забронировать</a>
+      <span></span><span></span><span></span>
+      <span>Рейтинг: 9,2</span>
+    </article>
+  </section>
+  <footer>
+    <section>
+      <h3>Наш хэштег и телефон:</h3>
+      <p>#visitsedona<br>
+        +7 800 555-86-28
+      </p>
+    </section>
+    <section>
+      <h3>Мы в соц. сетях:</h3>
+      <ul>
+        <li><a href="twitter.com">Twitter</a></li>
В случае ссылок на сторонние ресурсы, ссылку надо указывать начиная с протокола, иначе ссылка будет распознана как на папку внутри твоего проекта.In index.html:> +      <h2>Мало<br>
+        туристов</h2>
+      <span>&ndash; №5 &ndash;</span>
+      <p>Большинство едет в гранд-каньон и<br>
+        толпится там</p>
+    </section>
+    <section>
+      <h2>Заинтересовались?</h2>
+      <p>Укажите предполагаемые даты поездки,<br />
+        и мы покажем вам лучшие предложения гостиниц в седоне</p>
+      <a href="#">Поиск гостиницы в Седоне</a>
+    </section>
+    <footer>
+      <section>
+        <h3>Наш хэштег и телефон:</h3>
+        <p>#visitsedona<br>
Лучше в отдельные spanIn index.html:> +      <section>
+        <h3>Мы в соц. сетях:</h3>
+        <ul>
+          <li><a href="twitter.com">Twitter</a></li>
+          <li><a href="facebook.com">Facebook</a></li>
+          <li><a href="youtube.com">YouTube</a></li>
+        </ul>
+      </section>
+      <section>
+        <a href="https://htmlacademy.ru/intensive/htmlcss">Website by</a>
+      </section>
+    </footer>
+  </main>
+</body>
+
+</html>
Одна пустая строка в конце каждого файла.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

2021-05-30 04:41 UTC, Kubik1979 commented on catalog.html
> +      <input type="checkbox" name="pool" value="Бассейн" id="checkbox01" checked>
исправил

2021-05-30 04:43 UTC, Kubik1979 commented on catalog.html
> +      <span></span><span></span><span></span><span></span>
убрал пустые

2021-05-30 04:44 UTC, Kubik1979 commented on catalog.html
> +</html>
добавил в обоих файлах

2021-05-30 04:44 UTC, Kubik1979 commented on catalog.html
> +        <li><a href="twitter.com">Twitter</a></li>
скорректировал

2021-05-30 04:55 UTC, Kubik1979 commented on index.html
> +        <p>#visitsedona<br>
Вот здесь мне непонятно. 
Вот так?
<section>
        <span>#visitsedona</span><br>
        <span>+7 800 555-86-28</span>
      </section>

2021-05-30 04:58 UTC, Kubik1979 commented on index.html
> +</html>
Готово

2021-05-30 05:00 UTC, Kubik1979 commented on index.html
> +        <p>#visitsedona<br>
<span>#visitsedona</span><br>
<span>+7 800 555-86-28</span>

2021-06-03 10:00 UTC, merged